package lookup

object ClearFile {
  val FILE_A: Long = 0x7F7F7F7F7F7F7F7FL
  val FILE_B: Long = 0xBFBFBFBFBFBFBFBFL
  val FILE_C: Long = 0xDFDFDFDFDFDFDFDFL
  val FILE_D: Long = 0xEFEFEFEFEFEFEFEFL
  val FILE_E: Long = 0xF7F7F7F7F7F7F7F7L
  val FILE_F: Long = 0xFBFBFBFBFBFBFBFBL
  val FILE_G: Long = 0xFDFDFDFDFDFDFDFDL
  val FILE_H: Long = 0xFEFEFEFEFEFEFEFEL
}
