package lookup

object ClearRank {
  val RANK_1: Long = 0x00FFFFFFFFFFFFFFL
  val RANK_2: Long = 0xFF00FFFFFFFFFFFFL
  val RANK_3: Long = 0xFFFF00FFFFFFFFFFL
  val RANK_4: Long = 0xFFFFFF00FFFFFFFFL
  val RANK_5: Long = 0xFFFFFFFF00FFFFFFL
  val RANK_6: Long = 0xFFFFFFFFFF00FFFFL
  val RANK_7: Long = 0xFFFFFFFFFFFF00FFL
  val RANK_8: Long = 0xFFFFFFFFFFFFFF00L
}
